#!/usr/bin/env zsh
# encoding=UTF-8

#===============================================================================
#
#         FILE:  __expand("%")__
#
#        USAGE:  ---
#
#  DESCRIPTION:  ---
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  David M. Rosenberg <rosenbergdm@uchicago.edu>
#      COMPANY:  University of Chicago
#      VERSION:  1.0
#      CREATED:  __strftime("%D")__
#     REVISION:  ---
#===============================================================================




# vim: ft=zsh encoding=utf8 shiftwidth=4 softtabstop=4 expandtab
